### PR TITLE
F add player

### PR DESCRIPTION
**Pull request by chrishey**
Someone has been busy!

I like it, i am happy to pull it into master if everyone else is.

### CODE REVIEW

**Comment by chrishey** [comment]
I think we get this in and then we can move on to data access and working out the co-efficient. Maybe separate branches based off master once this PR is in?

**Comment by PatrickHalle** [comment]
Yeah sounds good glad you like it:) I need to write some tests for it still, will try and do that this weekend.

**Comment by PatrickHalle** [comment]
Why do you think we should go with NoSql?

**Comment by chrishey** [comment]
Completely selfish reasons that i want to play with Azure DocumentDB :-)

**Comment by PatrickHalle** [comment]
Ok that's cool I'm happy to go with a NoSQL DB. I'll get some tests written
up for adding a user over the weekend then we can merge in?

**Comment by chrishey** [comment]
I noticed we have 2 player models, i have tried to drag them together as the only extra property was player level. Next step would be to remove the duplicate, but want to talk it through with Paddy first.

**Comment by chrishey** [comment]
I am hoping to try and do half an hour a day on this, to keep learning and move it along. Not that i can play FIFA fridays for a while :-( Anyway....can we merge it?

**Comment by DSaunders** [comment]
I haven't really touched this with the lack of FIFA playing going on. Merge
away, I assume it will let you do it.

If you guys want to fork it go ahead, doesn't seem right me hosting it in
my name when I'm not contributing and you guys are doing the work on it
over there?

**Pull request merged**
